<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Financial Statement</title>
<style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'DejaVu Sans', sans-serif; font-size: 10px; color: #1e293b; background: #fff; }
    .header { background: #1e3a5f; color: #fff; padding: 18px 24px; margin-bottom: 20px; border-radius: 4px; }
    .header h1 { font-size: 20px; font-weight: bold; }
    .header p { font-size: 10px; color: #93c5fd; margin-top: 4px; }
    .summary { display: table; width: 100%; margin-bottom: 16px; }
    .summary-box { display: table-cell; width: 33%; padding: 12px 14px; border-radius: 4px; text-align: center; }
    .box-inflow { background: #dcfce7; border: 1px solid #86efac; }
    .box-outflow { background: #fee2e2; border: 1px solid #fca5a5; }
    .box-net { background: #dbeafe; border: 1px solid #93c5fd; }
    .summary-box .label { font-size: 8.5px; text-transform: uppercase; font-weight: 700; letter-spacing: 0.5px; color: #475569; }
    .summary-box .amount { font-size: 15px; font-weight: bold; margin-top: 4px; }
    .inflow-amount { color: #166534; }
    .outflow-amount { color: #991b1b; }
    .net-amount { color: #1d4ed8; }
    .spacer { width: 8px; display: table-cell; }
    table { width: 100%; border-collapse: collapse; margin-top: 4px; }
    thead tr { background: #1e3a5f; color: #fff; }
    thead th { padding: 9px 10px; text-align: left; font-size: 9px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; }
    tbody tr { border-bottom: 1px solid #e2e8f0; }
    tbody tr:nth-child(even) { background: #f8fafc; }
    tbody td { padding: 7px 10px; font-size: 9.5px; color: #334155; }
    .text-right { text-align: right; }
    .inflow { color: #166534; font-weight: bold; }
    .outflow { color: #991b1b; font-weight: bold; }
    .footer { margin-top: 20px; text-align: center; font-size: 8px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 10px; }
    .badge { display: inline-block; padding: 2px 7px; border-radius: 12px; font-size: 8px; font-weight: 700; }
    .badge-inflow { background: #dcfce7; color: #166534; }
    .badge-outflow { background: #fee2e2; color: #991b1b; }
</style>
</head>
<body>
<div class="header">
    <h1>The Sanctuary — Financial Statement</h1>
    <p>Generated by {{ $user->name }} ({{ $user->role_label }}) &nbsp;|&nbsp; {{ $date }}</p>
</div>

<div class="summary">
    <div class="summary-box box-inflow">
        <div class="label">Total Inflows</div>
        <div class="amount inflow-amount">₱{{ number_format($totalInflow, 2) }}</div>
    </div>
    <div class="spacer"></div>
    <div class="summary-box box-outflow">
        <div class="label">Total Outflows</div>
        <div class="amount outflow-amount">₱{{ number_format($totalOutflow, 2) }}</div>
    </div>
    <div class="spacer"></div>
    <div class="summary-box box-net">
        <div class="label">Net Cash Flow</div>
        <div class="amount net-amount">₱{{ number_format($net, 2) }}</div>
    </div>
</div>

<table>
    <thead>
        <tr>
            <th>#</th>
            <th>Date</th>
            <th>Society</th>
            <th>District / Conference</th>
            <th>Member</th>
            <th>Type</th>
            <th>Category</th>
            <th class="text-right">Amount (₱)</th>
            <th>Notes</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($donations as $i => $d)
        <tr>
            <td>{{ $i + 1 }}</td>
            <td>{{ \Carbon\Carbon::parse($d->donation_date)->format('M d, Y') }}</td>
            <td>{{ $d->localSociety->name ?? '—' }}</td>
            <td>{{ ($d->localSociety->district->name ?? '') }} / {{ ($d->localSociety->district->annualConference->name ?? '—') }}</td>
            <td>{{ $d->member ? $d->member->first_name . ' ' . $d->member->last_name : '—' }}</td>
            <td>
                <span class="badge {{ $d->type === 'inflow' ? 'badge-inflow' : 'badge-outflow' }}">
                    {{ ucfirst($d->type) }}
                </span>
            </td>
            <td>{{ $d->category }}</td>
            <td class="text-right {{ $d->type === 'inflow' ? 'inflow' : 'outflow' }}">
                {{ $d->type === 'inflow' ? '+' : '-' }}{{ number_format($d->amount, 2) }}
            </td>
            <td>{{ $d->notes ?? '—' }}</td>
        </tr>
        @endforeach
    </tbody>
</table>

<div class="footer">
    The Sanctuary Church Management System &nbsp;|&nbsp; Confidential &nbsp;|&nbsp; {{ $date }}
</div>
</body>
</html>
