<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Members Report</title>
<style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'DejaVu Sans', sans-serif; font-size: 10px; color: #1e293b; background: #fff; }
    .header { background: #1e3a5f; color: #fff; padding: 18px 24px; margin-bottom: 20px; border-radius: 4px; }
    .header h1 { font-size: 20px; font-weight: bold; letter-spacing: -0.5px; }
    .header p { font-size: 10px; color: #93c5fd; margin-top: 4px; }
    .meta { display: flex; justify-content: space-between; margin-bottom: 16px; padding: 0 2px; }
    .meta span { color: #64748b; font-size: 9px; }
    .meta strong { color: #1e293b; }
    table { width: 100%; border-collapse: collapse; }
    thead tr { background: #1e3a5f; color: #fff; }
    thead th { padding: 9px 10px; text-align: left; font-size: 9px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; }
    tbody tr { border-bottom: 1px solid #e2e8f0; }
    tbody tr:nth-child(even) { background: #f8fafc; }
    tbody td { padding: 8px 10px; font-size: 9.5px; color: #334155; }
    .badge { display: inline-block; padding: 2px 7px; border-radius: 12px; font-size: 8px; font-weight: 700; }
    .badge-active { background: #dcfce7; color: #166534; }
    .badge-inactive { background: #fee2e2; color: #991b1b; }
    .footer { margin-top: 20px; text-align: center; font-size: 8px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 10px; }
    .summary { background: #f0f9ff; border: 1px solid #bae6fd; border-radius: 4px; padding: 10px 14px; margin-bottom: 16px; font-size: 9.5px; }
    .summary strong { color: #0369a1; }
</style>
</head>
<body>
<div class="header">
    <h1>The Sanctuary — Members Report</h1>
    <p>Generated by {{ $user->name }} ({{ $user->role_label }}) &nbsp;|&nbsp; {{ $date }}</p>
</div>

<div class="summary">
    Total Members: <strong>{{ $members->count() }}</strong> &nbsp;&nbsp;
    Active: <strong>{{ $members->where('status', 'Active')->count() }}</strong> &nbsp;&nbsp;
    Inactive: <strong>{{ $members->where('status', 'Inactive')->count() }}</strong>
</div>

<table>
    <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Gender</th>
            <th>Status</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Society</th>
            <th>District</th>
            <th>Conference</th>
            <th>Member Since</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($members as $i => $m)
        <tr>
            <td>{{ $i + 1 }}</td>
            <td><strong>{{ $m->last_name }}, {{ $m->first_name }}</strong></td>
            <td>{{ $m->gender ?? '—' }}</td>
            <td>
                <span class="badge {{ $m->status === 'Active' ? 'badge-active' : 'badge-inactive' }}">
                    {{ $m->status }}
                </span>
            </td>
            <td>{{ $m->email ?? '—' }}</td>
            <td>{{ $m->phone ?? '—' }}</td>
            <td>{{ $m->localSociety->name ?? '—' }}</td>
            <td>{{ $m->localSociety->district->name ?? '—' }}</td>
            <td>{{ $m->localSociety->district->annualConference->name ?? '—' }}</td>
            <td>{{ $m->membership_date ? $m->membership_date->format('M d, Y') : '—' }}</td>
        </tr>
        @endforeach
    </tbody>
</table>

<div class="footer">
    The Sanctuary Church Management System &nbsp;|&nbsp; Confidential &nbsp;|&nbsp; {{ $date }}
</div>
</body>
</html>
