<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Ministry Member Roster</title>
<style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'DejaVu Sans', sans-serif; font-size: 10px; color: #1e293b; background: #fff; }
    .header { background: #1e3a5f; color: #fff; padding: 18px 24px; margin-bottom: 20px; border-radius: 4px; }
    .header h1 { font-size: 20px; font-weight: bold; }
    .header p { font-size: 10px; color: #93c5fd; margin-top: 4px; }
    .summary { background: #f0f9ff; border: 1px solid #bae6fd; border-radius: 4px; padding: 10px 14px; margin-bottom: 16px; font-size: 9.5px; }
    .summary strong { color: #0369a1; }
    table { width: 100%; border-collapse: collapse; }
    thead tr { background: #1e3a5f; color: #fff; }
    thead th { padding: 9px 10px; text-align: left; font-size: 9px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; }
    tbody tr { border-bottom: 1px solid #e2e8f0; }
    tbody tr:nth-child(even) { background: #f8fafc; }
    tbody td { padding: 8px 10px; font-size: 9.5px; color: #334155; }
    .footer { margin-top: 20px; text-align: center; font-size: 8px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 10px; }
</style>
</head>
<body>
<div class="header">
    <h1>{{ $ministry->name }} — Member Roster</h1>
    <p>Generated by {{ $user->name }} ({{ $user->role_label }}) &nbsp;|&nbsp; {{ $date }}</p>
</div>

<div class="summary">
    Leader: <strong>{{ $ministry->leader_name ?? 'No National Leader Assigned' }}</strong> &nbsp;&nbsp;
    Total Members (Scoped): <strong>{{ $members->count() }}</strong>
</div>

<table>
    <thead>
        <tr>
            <th>#</th>
            <th>Member Name</th>
            <th>Society</th>
            <th>District</th>
            <th>Contact</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($members as $i => $m)
        <tr>
            <td>{{ $i + 1 }}</td>
            <td><strong>{{ $m->first_name }} {{ $m->last_name }}</strong></td>
            <td>{{ $m->localSociety->name }}</td>
            <td>{{ $m->localSociety->district->name }}</td>
            <td>{{ $m->phone ?? $m->email ?? '—' }}</td>
            <td>{{ $m->status }}</td>
        </tr>
        @endforeach
    </tbody>
</table>

<div class="footer">
    The Sanctuary Church Management System &nbsp;|&nbsp; Confidential &nbsp;|&nbsp; {{ $date }}
</div>
</body>
</html>
